import { Aspect, Tag } from 'src/models/Index';

const Aspects: Aspect[] = [
  {
    name: 'Alchemy',
    tagName: 'Alchemy',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Feasts', 'Blood', 'Creation', 'Knowledge', 'Water'],
    enemyAspects: ['Shadow', 'Frost', 'Wind'],
  },
  {
    name: 'Art & Music',
    tagName: 'Art',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Feasts', 'Love', 'Creation', 'Moon', 'Day', 'Wind'],
    enemyAspects: ['Beasts', 'Destruction', 'Flame', 'Honor'],
  },
  {
    name: 'Battle',
    tagName: 'Battle',
    description: 'god of blattle and combat bro',
    altDescription: 'NONE',
    friendlyAspects: [
      'Might',
      'Forge',
      'Blood',
      'Pain',
      'Destruction',
      'Honor',
    ],
    enemyAspects: ['Love', 'Commerce', 'Humility'],
  },
  {
    name: 'Beasts',
    tagName: 'Beasts',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Nature', 'Blood', 'Might', 'Moon'],
    enemyAspects: ['Magic', 'Commerce', 'Plague', 'Flame', 'Frost'],
  },
  {
    name: 'Blood',
    tagName: 'Blood',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [
      'Pain',
      'Battle',
      'Alchemy',
      'Death',
      'Life',
      'Madness',
      'Magic',
    ],
    enemyAspects: ['Flame', 'Frost', 'Light', 'Stone'],
  },
  {
    name: 'Chaos',
    tagName: 'Chaos',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Madness', 'Magic', 'Moon', 'Stars', 'Destruction'],
    enemyAspects: [
      'Life',
      'Light',
      'Death',
      'Shadow',
      'Commerce',
      'Honor',
      'Creation',
      'Humility',
    ],
  },
  {
    name: 'Commerce',
    tagName: 'Commerce',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Trickery', 'Feasts', 'Art', 'Forge', 'Wind', 'Water'],
    enemyAspects: ['Humility', 'Honor', 'Destruction', 'Plague', 'Death'],
  },
  {
    name: 'Creation',
    tagName: 'Creation',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Life', 'Light', 'Love', 'Alchemy', 'Forge', 'Art'],
    enemyAspects: ['Destruction', 'Chaos', 'Battle'],
  },
  {
    name: 'Darkness',
    tagName: 'Shadow',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Death', 'Trickery', 'Pain', 'Moon', 'Stars'],
    enemyAspects: ['Light', 'Day', 'Flame', 'Feasts'],
  },
  {
    name: 'Death',
    tagName: 'Death',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Destruction', 'Shadow', 'Stone', 'Knowledge', 'Blood'],
    enemyAspects: ['Life', 'Creation', 'Feasts', 'Art', 'Chaos', 'Love'],
  },
  {
    name: 'Destruction',
    tagName: 'Destruction',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Death', 'Chaos', 'Madness', 'Flame', 'Plague'],
    enemyAspects: ['Creation', 'Life', 'Light', 'Honor', 'Humility', 'Art'],
  },
  {
    name: 'Flame',
    tagName: 'Flame',
    description: 'fire',
    altDescription: 'NONE',
    friendlyAspects: ['Day', 'Forge', 'Magic', 'Light', 'Storm'],
    enemyAspects: ['Frost', 'Water', 'Commerce', 'Beasts'],
  },
  {
    name: 'Food & Drink',
    tagName: 'Feasts',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Art', 'Commerce', 'Life', 'Nature', 'Beasts'],
    enemyAspects: ['Frost', 'Death', 'Humility', 'Destruction'],
  },
  {
    name: 'Frost',
    tagName: 'Frost',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Water', 'Magic', 'Shadow', 'Knowledge', 'Time', 'Moon'],
    enemyAspects: ['Flame', 'Day', 'Nature', 'Feasts', 'Plague'],
  },
  {
    name: 'Honor',
    tagName: 'Honor',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Battle', 'Forge', 'Might', 'Humility', 'Blood', 'Stone'],
    enemyAspects: [
      'Commerce',
      'Trickery',
      'Magic',
      'Shadow',
      'Madness',
      'Plague',
    ],
  },
  {
    name: 'Humility',
    tagName: 'Humility',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Honor', 'Forge', 'Knowledge', 'Light', 'Love', 'Time'],
    enemyAspects: [
      'Battle',
      'Magic',
      'Commerce',
      'Destruction',
      'Chaos',
      'Madness',
      'Trickery',
    ],
  },
  {
    name: 'Knowledge',
    tagName: 'Knowledge',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Magic', 'Alchemy', 'Creation', 'Nature', 'Stars'],
    enemyAspects: ['Destruction', 'Death', 'Might', 'Flame', 'Madness'],
  },
  {
    name: 'Life',
    tagName: 'Life',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Light', 'Creation', 'Love', 'Nature', 'Beasts', 'Blood'],
    enemyAspects: [
      'Death',
      'Destruction',
      'Chaos',
      'Madness',
      'Frost',
      'Stone',
    ],
  },
  {
    name: 'Light',
    tagName: 'Light',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Humility', 'Life', 'Creation', 'Love', 'Day', 'Storm'],
    enemyAspects: ['Shadow', 'Death', 'Chaos', 'Frost', 'Blood'],
  },
  {
    name: 'Love',
    tagName: 'Love',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Life', 'Nature', 'Madness', 'Moon', 'Creation', 'Art'],
    enemyAspects: ['Destruction', 'Death', 'Frost', 'Battle', 'Beasts'],
  },
  {
    name: 'Madness',
    tagName: 'Madness',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [
      'Moon',
      'Stars',
      'Chaos',
      'Blood',
      'Pain',
      'Water',
      'Destruction',
    ],
    enemyAspects: [
      'Light',
      'Death',
      'Creation',
      'Honor',
      'Humility',
      'Stone',
      'Forge',
    ],
  },
  {
    name: 'Magic',
    tagName: 'Magic',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [
      'Flame',
      'Frost',
      'Storm',
      'Wind',
      'Knowledge',
      'Alchemy',
    ],
    enemyAspects: ['Might', 'Forge', 'Trickery', 'Light'],
  },
  {
    name: 'Might',
    tagName: 'Might',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Battle', 'Pain', 'Honor', 'Forge'],
    enemyAspects: ['Magic', 'Alchemy', 'Art', 'Trickery'],
  },
  {
    name: 'Nature',
    tagName: 'Nature',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Beasts', 'Life', 'Feasts', 'Stone', 'Water', 'Wind'],
    enemyAspects: ['Flame', 'Frost', 'Plague', 'Stars'],
  },
  {
    name: 'Pain',
    tagName: 'Pain',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Blood', 'Battle', 'Plague', 'Time'],
    enemyAspects: ['Light', 'Life', 'Stone', 'Storm'],
  },
  {
    name: 'Plague',
    tagName: 'Plague',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [
      'Blood',
      'Pain',
      'Shadow',
      'Chaos',
      'Madness',
      'Destruction',
    ],
    enemyAspects: [
      'Nature',
      'Light',
      'Life',
      'Storm',
      'Stone',
      'Forge',
      'Love',
      'Creation',
      'Day',
      'Humility',
      'Honor',
      'Beasts',
    ],
  },
  {
    name: 'Revelry',
    tagName: 'Revelry',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [
      'Feasts',
      'Art',
      'Madness',
      'Love',
      'Moon',
      'Stars',
      'Trickery',
    ],
    enemyAspects: ['Honor', 'Storm', 'Light', 'Death', 'Plague'],
  },
  {
    name: 'Stone',
    tagName: 'Stone',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Forge', 'Nature', 'Moon', 'Humility', 'Honor'],
    enemyAspects: ['Plague', 'Flame', 'Magic', 'Love', 'Destruction', 'Blood'],
  },
  {
    name: 'The Forge',
    tagName: 'Forge',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Flame', 'Might', 'Battle', 'Stone', 'Creation'],
    enemyAspects: ['Plague', 'Frost', 'Shadow', 'Death', 'Water'],
  },
  {
    name: 'The Moon',
    tagName: 'Moon',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [
      'Madness',
      'Stone',
      'Storm',
      'Stars',
      'Shadow',
      'Trickery',
    ],
    enemyAspects: ['Day', 'Flame', 'Light', 'Honor'],
  },
  {
    name: 'The Sea',
    tagName: 'Water',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Alchemy', 'Wind', 'Commerce', 'Nature', 'Life', 'Frost'],
    enemyAspects: ['Flame', 'Day', 'Death', 'Storm', 'Stone', 'Forge'],
  },
  {
    name: 'The Sky',
    tagName: 'Storm',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Moon', 'Stars', 'Light', 'Day'],
    enemyAspects: ['Death', 'Shadow', 'Chaos', 'Madness'],
  },
  {
    name: 'The Stars',
    tagName: 'Stars',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: ['Madness', 'Chaos', 'Day', 'Moon', 'Frost'],
    enemyAspects: [],
  },
  {
    name: 'The Sun',
    tagName: 'Day',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [],
    enemyAspects: [],
  },
  {
    name: 'Time',
    tagName: 'Time',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [],
    enemyAspects: [],
  },
  {
    name: 'Trickery',
    tagName: 'Trickery',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [],
    enemyAspects: [],
  },
  {
    name: 'Wind',
    tagName: 'Wind',
    description: 'NONE',
    altDescription: 'NONE',
    friendlyAspects: [],
    enemyAspects: [],
  },
];

export function getAspect(tagName: Tag): Aspect {
  let result = Aspects.find((element) => element.tagName === tagName);
  if (!result) result = Aspects[0];
  return result;
}

export function getAllAspects(): Aspect[] {
  return Aspects.slice();
}

export function getAllAspectTags(): string[] {
  const result = [];
  for (let i = 0; i < Aspects.length; i++) {
    result.push(Aspects[i].tagName);
  }
  return result;
}
