import { ModType, Tag } from "src/models/Index";
import Mod from "src/models/Mod";
import {
  getModByCriteria,
  prepareModForExport,
} from "src/Services/ModListManipulationService";

const modType: ModType = "BASE";

/*
importantA: ,
    importantB: ,
    importantC: ,
*/

const ModList: Partial<Mod>[] = [
  //debug
  {
    name: "Invalid Item",
    description:
      "whoops this item is bugged please submit a bug report also what were you doing when this item appeared",
    rarity: 9999,
    inventoryIcon: new URL("src/assets/Icons/error.png", import.meta.url),
    slot: "Quest Item",
    tags: [],
  },
  {
    name: "2HanderDummyItem",
    description: "",
    rarity: 9999,
    inventoryIcon: new URL("src/assets/Icons/2hander.png", import.meta.url),
    slot: "Quest Item",
    tags: [],
  },
  //light weapon
  {
    name: "Dagger",
    description: "",
    rarity: 0,
    importantA: "Accuracy",
    importantB: "Attack",
    importantC: "CriticalChance",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/Dagger.png",
      import.meta.url
    ),
    slot: "Light Weapon",
    tags: [
      "Blade",
      "Weapon",
      "Stabbing",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Piercing",
  },
  {
    name: "Hatchet",
    description: "",
    rarity: 0,
    importantA: "Accuracy",
    importantB: "Attack",
    importantC: "CriticalDamage",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/hatchet.png",
      import.meta.url
    ),
    slot: "Light Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Dirk",
    description: "",
    rarity: 0,
    importantA: "Accuracy",
    importantB: "Attack",
    importantC: "Arcana",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/Dagger.png",
      import.meta.url
    ),
    slot: "Light Weapon",
    tags: [
      "Blade",
      "Weapon",
      "Stabbing",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Piercing",
  },
  {
    name: "Shortsword",
    description: "",
    rarity: 0,
    importantA: "Accuracy",
    importantB: "Attack",
    importantC: "Deflect",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Sword001.png",
      import.meta.url
    ),
    slot: "Light Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Knife",
    description: "",
    rarity: 0,
    importantA: "Accuracy",
    importantB: "Attack",
    importantC: "Evasion",
    Survival: 1,
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/Dagger.png",
      import.meta.url
    ),
    slot: "Light Weapon",
    tags: [
      "Blade",
      "Weapon",
      "Stabbing",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Piercing",
  },
  {
    name: "Washizaki",
    description: "",
    rarity: 0,
    importantA: "Accuracy",
    importantB: "Attack",
    importantC: "Block",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Dagger004.png",
      import.meta.url
    ),
    slot: "Light Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Maingauche",
    description: "",
    rarity: 0,
    importantA: "Accuracy",
    importantB: "Attack",
    importantC: "Parry",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Dagger004.png",
      import.meta.url
    ),
    slot: "Light Weapon",
    tags: [
      "Blade",
      "Weapon",
      "Stabbing",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Piercing",
  },
  //medium weapons
  {
    name: "Sabre",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "CriticalChance",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Sword001.png",
      import.meta.url
    ),
    slot: "Medium Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Axe",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "CriticalDamage",
    inventoryIcon: new URL("src/assets/Icons/Weapons/Axe.png", import.meta.url),
    slot: "Medium Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Hammer",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "Impact",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Mace003.png",
      import.meta.url
    ),
    slot: "Medium Weapon",
    tags: [
      "Blunt",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Club",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Clarity",
    importantC: "Impact",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Mace002.png",
      import.meta.url
    ),
    slot: "Medium Weapon",
    tags: [
      "Blunt",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Sword",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "Deflect",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Sword003.png",
      import.meta.url
    ),
    slot: "Medium Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Katar",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Block",
    importantC: "Accuracy",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/VHWeapon.png",
      import.meta.url
    ),
    slot: "Medium Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Rapier",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "Parry",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Sword003.png",
      import.meta.url
    ),
    slot: "Medium Weapon",
    tags: [
      "Stabbing",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Piercing",
  },
  {
    name: "Mace",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "Fortitude",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Mace004.png",
      import.meta.url
    ),
    slot: "Medium Weapon",
    tags: [
      "Blunt",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Machete",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "Evasion",
    Survival: 1,
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Dagger004.png",
      import.meta.url
    ),
    slot: "Medium Weapon",
    tags: [
      "Blunt",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  //heavy weapons
  {
    name: "Spear",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "CriticalChance",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Spear005.png",
      import.meta.url
    ),
    slot: "Heavy Weapon",
    tags: [
      "Stabbing",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Piercing",
  },
  {
    name: "Battleaxe",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "CriticalDamage",
    importantC: "Accuracy",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Axe003.png",
      import.meta.url
    ),
    slot: "Heavy Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Quarterstaff",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Clarity",
    importantC: "Accuracy",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Staff01.png",
      import.meta.url
    ),
    slot: "Heavy Weapon",
    tags: [
      "Blunt",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Longsword",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Deflect",
    importantC: "Accuracy",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Sword008.png",
      import.meta.url
    ),
    slot: "Heavy Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Katana",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Block",
    importantC: "Accuracy",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Sword008.png",
      import.meta.url
    ),
    slot: "Heavy Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Flail",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Fortitude",
    importantC: "Accuracy",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Mace005.png",
      import.meta.url
    ),
    slot: "Heavy Weapon",
    tags: [
      "Blunt",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Pickaxe",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Deflect",
    importantC: "Impact",
    Mining: 2,
    inventoryIcon: new URL(
      "src/assets/Icons/Tools/pickaxe3.png",
      import.meta.url
    ),
    slot: "Heavy Weapon",
    tags: ["Tool", "Weapon", "allow_GEM", "allow_METAL", "allow_STONE"],
    attackType: "Physical",
  },
  {
    name: "Shovel",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Deflect",
    importantC: "CriticalChance",
    Mining: 1,
    inventoryIcon: new URL(
      "src/assets/Icons/Tools/shovel3.png",
      import.meta.url
    ),
    slot: "Heavy Weapon",
    tags: [
      "Tool",
      "Weapon",
      "Polearm",
      "Blade",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  //veryheavy weapons
  {
    name: "Halberd",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Impact",
    importantC: "Accuracy",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Axe007.png",
      import.meta.url
    ),
    slot: "Very Heavy Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Pike",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Accuracy",
    importantC: "Impact",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Spear005.png",
      import.meta.url
    ),
    slot: "Very Heavy Weapon",
    tags: [
      "Stabbing",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Piercing",
  },
  {
    name: "Bardiche",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Impact",
    importantC: "CriticalDamage",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Axe007.png",
      import.meta.url
    ),
    slot: "Very Heavy Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Warhammer",
    description: "",
    rarity: 0,
    importantA: "Impact",
    importantB: "Attack",
    importantC: "CriticalDamage",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/warhammer.png",
      import.meta.url
    ),
    slot: "Very Heavy Weapon",
    tags: [
      "Blunt",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Scythe",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Impact",
    importantC: "Arcana",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/scythe2.png",
      import.meta.url
    ),
    slot: "Very Heavy Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Greatstaff",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Impact",
    importantC: "Clarity",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Staff01.png",
      import.meta.url
    ),
    slot: "Very Heavy Weapon",
    tags: [
      "Blunt",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Greatsword",
    description: "",
    rarity: 0,
    importantA: "Attack",
    importantB: "Impact",
    importantC: "Deflect",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Sword022.png",
      import.meta.url
    ),
    slot: "Very Heavy Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  {
    name: "Broadsword",
    description: "",
    rarity: 0,
    importantA: "Deflect",
    importantB: "Attack",
    importantC: "Impact",
    inventoryIcon: new URL(
      "src/assets/Icons/Weapons/W_Sword022.png",
      import.meta.url
    ),
    slot: "Very Heavy Weapon",
    tags: [
      "Blade",
      "Weapon",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
    attackType: "Physical",
  },
  //implement
  {
    name: "Orb",
    description: "",
    rarity: 0,
    importantA: "Arcana",
    importantB: "Clarity",
    importantC: "WIL",
    inventoryIcon: new URL(
      "src/assets/Icons/Implements/misc_crystal_new.png",
      import.meta.url
    ),
    slot: "Implement",
    tags: [
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
  },
  {
    name: "Tome",
    description: "",
    rarity: 0,
    importantA: "Arcana",
    importantB: "Clarity",
    importantC: "INT",
    inventoryIcon: new URL(
      "src/assets/Icons/Books/bookmark_old.png",
      import.meta.url
    ),
    slot: "Implement",
    tags: ["allow_BONE", "allow_LEATHER", "allow_PARCHMENT"],
  },
  {
    name: "Rod",
    description: "",
    rarity: 0,
    importantA: "Arcana",
    importantB: "Clarity",
    importantC: "STR",
    inventoryIcon: new URL(
      "src/assets/Icons/Implements/rod_7_old.png",
      import.meta.url
    ),
    slot: "Implement",
    tags: [
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
  },
  {
    name: "Symbol",
    description: "",
    rarity: 0,
    importantA: "Clarity",
    importantB: "Arcana",
    importantC: "FAI",
    inventoryIcon: new URL(
      "src/assets/Icons/Implements/misc_lamp_new.png",
      import.meta.url
    ),
    slot: "Implement",
    tags: [
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
      "allow_PARCHMENT",
    ],
  },
  {
    name: "Totem",
    description: "",
    rarity: 0,
    importantA: "Arcana",
    importantB: "VIT",
    importantC: "Clarity",
    inventoryIcon: new URL(
      "src/assets/Icons/Implements/rod_forked.png",
      import.meta.url
    ),
    slot: "Implement",
    tags: [
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
  },
  {
    name: "Wand",
    description: "",
    rarity: 0,
    importantA: "INT",
    importantB: "Arcana",
    importantC: "Clarity",
    inventoryIcon: new URL(
      "src/assets/Icons/Implements/rod_9_old.png",
      import.meta.url
    ),
    slot: "Implement",
    tags: [
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_STONE",
      "allow_WOOD",
    ],
  },
  //light instrument
  {
    name: "Bell",
    description: "",
    rarity: 0,
    importantA: "Clarity",
    importantB: "Diplomacy",
    importantC: "CHA",
    inventoryIcon: new URL("src/assets/Icons/placeholder.png", import.meta.url),
    slot: "Instrument",
    tags: ["Instrument", "allow_BONE", "allow_GEM", "allow_METAL"],
  },
  {
    name: "Horn",
    description: "",
    rarity: 0,
    importantA: "Arcana",
    importantB: "Leadership",
    importantC: "CHA",
    inventoryIcon: new URL("src/assets/Icons/placeholder.png", import.meta.url),
    slot: "Instrument",
    tags: ["Instrument", "allow_BONE", "allow_METAL", "allow_WOOD"],
  },

  //heavy instrument
  {
    name: "Lute",
    description: "",
    rarity: 0,
    importantA: "CHA",
    importantB: "Bargaining",
    importantC: "Clarity",
    inventoryIcon: new URL("src/assets/Icons/placeholder.png", import.meta.url),
    slot: "Instrument",
    tags: [
      "Instrument",
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_WOOD",
    ],
  },
  {
    name: "Drum",
    description: "",
    rarity: 0,
    importantA: "CHA",
    importantB: "Leadership",
    importantC: "Supression",
    inventoryIcon: new URL("src/assets/Icons/placeholder.png", import.meta.url),
    slot: "Instrument",
    tags: ["Instrument", "allow_BONE", "allow_METAL", "allow_WOOD"],
  },
  {
    name: "Flute",
    description: "",
    rarity: 0,
    importantA: "CHA",
    importantB: "Diplomacy",
    importantC: "Clarity",
    inventoryIcon: new URL("src/assets/Icons/placeholder.png", import.meta.url),
    slot: "Instrument",
    tags: ["Instrument", "allow_BONE", "allow_METAL", "allow_WOOD"],
  },

  /////

  {
    name: "Cap",
    description: "",
    rarity: 0,
    importantA: "Armor",
    importantB: "Resolve",
    importantC: "Fortitude",
    inventoryIcon: new URL("src/assets/Icons/Helmets/Cap.png", import.meta.url),
    slot: "Light Helmet",
    tags: [
      "allow_BONE",
      "allow_CLOTH",
      "allow_HIDE",
      "allow_LEATHER",
      "allow_METAL",
    ],
  },
  {
    name: "Hat",
    description: "",
    rarity: 0,
    importantA: "Armor",
    importantB: "Clarity",
    importantC: "Resolve",
    inventoryIcon: new URL(
      "src/assets/Icons/Helmets/elven_leather_helm.png",
      import.meta.url
    ),
    slot: "Light Helmet",
    tags: [
      "allow_BONE",
      "allow_CLOTH",
      "allow_HIDE",
      "allow_LEATHER",
      "allow_METAL",
    ],
  },
  {
    name: "Helm",
    description: "",
    rarity: 0,
    importantA: "Armor",
    importantB: "Fortitude",
    importantC: "Armor",
    Armor: 1,
    inventoryIcon: new URL(
      "src/assets/Icons/Helmets/Helm.png",
      import.meta.url
    ),
    slot: "Medium Helmet",
    tags: ["allow_BONE", "allow_METAL", "allow_WOOD", "allow_STONE"],
  },
  {
    name: "Cloak",
    description: "",
    rarity: 0,
    importantA: "Evasion",
    importantB: "Armor",
    importantC: "Ward",
    inventoryIcon: new URL("src/assets/Icons/Armor/Cloak.png", import.meta.url),
    slot: "Light Armor",
    tags: ["allow_CLOTH", "allow_HIDE", "allow_LEATHER"],
  },
  {
    name: "Cape",
    description: "",
    rarity: 0,
    importantA: "Resolve",
    importantB: "Fortitude",
    importantC: "Leadership",
    inventoryIcon: new URL("src/assets/Icons/Armor/Cloak.png", import.meta.url),
    slot: "Light Armor",
    tags: ["Cape", "allow_CLOTH", "allow_HIDE", "allow_LEATHER"],
  },
  {
    name: "Robes",
    description: "",
    rarity: 0,
    importantA: "Ward",
    importantB: "Clarity",
    importantC: "FAI",
    Clarity: 1,
    inventoryIcon: new URL(
      "src/assets/Icons/Armor/cloak_2.png",
      import.meta.url
    ),
    slot: "Light Armor",
    tags: ["allow_CLOTH", "allow_HIDE", "allow_LEATHER"],
  },
  {
    name: "Tunic",
    description: "",
    rarity: 0,
    importantA: "STR",
    importantB: "Accuracy",
    importantC: "Armor",
    inventoryIcon: new URL(
      "src/assets/Icons/Armor/A_Clothing02.png",
      import.meta.url
    ),
    slot: "Light Armor",
    tags: ["allow_CLOTH", "allow_HIDE", "allow_LEATHER"],
  },
  {
    name: "Jerkin",
    description: "",
    rarity: 0,
    importantA: "Armor",
    importantB: "Evasion",
    importantC: "Armor",
    Armor: 1,
    inventoryIcon: new URL(
      "src/assets/Icons/Armor/Jerkin.png",
      import.meta.url
    ),
    slot: "Medium Armor",
    tags: ["allow_CLOTH", "allow_HIDE", "allow_LEATHER"],
  },
  {
    name: "Chainmail",
    description: "",
    rarity: 0,
    importantA: "Armor",
    importantB: "Deflect",
    importantC: "Armor",
    Armor: 2,
    AGI: -1,
    inventoryIcon: new URL("src/assets/Icons/Armor/Armor.png", import.meta.url),
    slot: "Heavy Armor",
    tags: ["allow_METAL"],
  },
  {
    name: "Buckler",
    description: "",
    rarity: 0,
    importantA: "Block",
    importantB: "Evasion",
    importantC: "Resolve",
    inventoryIcon: new URL(
      "src/assets/Icons/Shields/Buckler.png",
      import.meta.url
    ),
    slot: "Light Shield",
    tags: ["allow_BONE", "allow_GEM", "allow_METAL", "allow_WOOD"],
  },
  {
    name: "Kite Shield",
    description: "",
    rarity: 0,
    importantA: "Block",
    importantB: "Deflect",
    importantC: "Resolve",
    Block: 1,
    inventoryIcon: new URL(
      "src/assets/Icons/Shields/Kite.png",
      import.meta.url
    ),
    slot: "Medium Shield",
    tags: ["allow_BONE", "allow_GEM", "allow_METAL", "allow_WOOD"],
  },
  {
    name: "Tower Shield",
    description: "",
    rarity: 0,
    importantA: "Block",
    importantB: "Deflect",
    importantC: "Fortitude",
    Block: 2,
    inventoryIcon: new URL(
      "src/assets/Icons/Shields/Tower.png",
      import.meta.url
    ),
    slot: "Heavy Shield",
    tags: [
      "allow_BONE",
      "allow_GEM",
      "allow_METAL",
      "allow_WOOD",
      "allow_STONE",
    ],
  },
  {
    name: "Gloves",
    description: "",
    rarity: 0,
    importantA: "Armor",
    importantB: "DEX",
    importantC: "Accuracy",
    inventoryIcon: new URL(
      "src/assets/Icons/Gloves/Gloves.png",
      import.meta.url
    ),
    slot: "Gloves",
    tags: ["allow_CLOTH", "allow_HIDE", "allow_LEATHER", "allow_METAL"],
  },
  {
    name: "Boots",
    description: "",
    rarity: 0,
    importantA: "Armor",
    importantB: "AGI",
    importantC: "Evasion",
    inventoryIcon: new URL("src/assets/Icons/Boots/Boots.png", import.meta.url),
    slot: "Boots",
    tags: ["allow_CLOTH", "allow_HIDE", "allow_LEATHER", "allow_METAL"],
  },
  {
    name: "Belt",
    description: "",
    rarity: 0,
    importantA: "Fortitude",
    importantB: "Resolve",
    importantC: "price",
    inventoryIcon: new URL("src/assets/Icons/Items/Belt.png", import.meta.url),
    slot: "Belt",
    tags: ["allow_CLOTH", "allow_HIDE", "allow_LEATHER", "allow_METAL"],
  },
  {
    name: "Ring",
    description: "",
    rarity: 0,
    importantA: "price",
    importantB: "priceMultiplier",
    importantC: "Arcana",
    inventoryIcon: new URL(
      "src/assets/Icons/Trinkets/Ring1.png",
      import.meta.url
    ),
    slot: "Trinket",
    tags: ["allow_METAL", "allow_BONE"],
  },
  {
    name: "Amulet",
    description: "",
    rarity: 0,
    importantA: "price",
    importantB: "Ward",
    importantC: "Supression",
    inventoryIcon: new URL(
      "src/assets/Icons/Trinkets/Ac_Necklace02.png",
      import.meta.url
    ),
    slot: "Trinket",
    tags: ["allow_METAL", "allow_BONE"],
  },
  {
    name: "Necklace",
    description: "",
    rarity: 0,
    importantA: "price",
    importantB: "priceMultiplier",
    importantC: "Clarity",
    inventoryIcon: new URL(
      "src/assets/Icons/Trinkets/Ac_Necklace02.png",
      import.meta.url
    ),
    slot: "Trinket",
    tags: ["allow_METAL", "allow_BONE"],
  },
  {
    name: "Bracelet",
    description: "",
    rarity: 0,
    importantA: "price",
    importantB: "priceMultiplier",
    importantC: "Resolve",
    inventoryIcon: new URL(
      "src/assets/Icons/Trinkets/Ac_Ring02.png",
      import.meta.url
    ),
    slot: "Trinket",
    tags: ["allow_METAL", "allow_BONE"],
  },
  {
    name: "Herbalist's Pouch",
    description: "",
    rarity: 0,
    importantA: "Medicine",
    importantB: "Survival",
    importantC: "price",
    inventoryIcon: new URL("src/assets/Icons/Items/bag.png", import.meta.url),
    slot: "Implement",
    tags: ["Tool", "allow_CLOTH", "allow_LEATHER"],
  },
];

export function getBaseModByIndex(index: number): Mod {
  if (index < 0) index = 0;
  const result = ModList[index];
  return prepareModForExport(result, modType);
}

export function getBaseModByName(name: string): Mod {
  const index = ModList.findIndex(
    (element) => element.name?.toLowerCase() === name?.toLowerCase()
  );
  return getBaseModByIndex(index);
}

export function getBaseModByCriteria(
  tags: Tag[],
  minRarity: number,
  maxRarity: number,
  exclusionTags: Tag[] = [],
  mustHaveTags: Tag[] = []
): Mod {
  return getModByCriteria(
    ModList,
    modType,
    tags,
    minRarity,
    maxRarity,
    exclusionTags,
    mustHaveTags
  );
}
